import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { generateSessionsForSchedule } from '../common/utils/session-generator.util';
import { CreateProgramScheduleDto } from './dto/create-program-schedule.dto';
import { UpdateProgramScheduleDto } from './dto/update-program-schedule.dto';

@Injectable()
export class ProgramSchedulesService {
  constructor(private readonly prisma: DatabaseService) {}

  /**
   * Adds a new schedule to an existing ProgramLocation and generates future sessions.
   */
  async create(dto: CreateProgramScheduleDto) {
    const programLocation = await this.prisma.programLocation.findUnique({
      where: { id: dto.programLocationId },
      include: { program: true },
    });

    if (!programLocation) {
      throw new NotFoundException('Program location not found.');
    }

    return this.prisma.$transaction(async (prisma) => {
      const { programLocationId, ...scheduleData } = dto;

      const schedule = await prisma.programSchedule.create({
        data: { ...scheduleData, programLocationId },
      });

      const today = new Date();
      today.setUTCHours(0, 0, 0, 0);
      const programEnd = new Date(programLocation.program.endDate);
      const start = today > new Date(programLocation.program.startDate)
        ? today
        : new Date(programLocation.program.startDate);

      const payloads = generateSessionsForSchedule(
        programLocationId,
        { ...scheduleData, id: schedule.id },
        start,
        programEnd,
      );

      if (payloads.length > 0) {
        await prisma.programSession.createMany({ data: payloads });
      }

      return schedule;
    });
  }

  async findOne(id: string) {
    const schedule = await this.prisma.programSchedule.findUnique({
      where: { id },
      include: { programLocation: { include: { program: true } } },
    });

    if (!schedule) throw new NotFoundException('Program schedule not found.');
    return schedule;
  }

  /**
   * Updates a schedule and regenerates all future sessions tied to it.
   */
  async update(id: string, dto: UpdateProgramScheduleDto) {
    const existing = await this.findOne(id);

    return this.prisma.$transaction(async (prisma) => {
      const today = new Date();
      today.setUTCHours(0, 0, 0, 0);

      // Delete future sessions that were generated by this schedule
      await prisma.programSession.deleteMany({
        where: { scheduleId: id, date: { gte: today } },
      });

      const updated = await prisma.programSchedule.update({
        where: { id },
        data: dto,
      });

      const programEnd = new Date(
        existing.programLocation.program.endDate,
      );

      const start =
        today > new Date(existing.programLocation.program.startDate)
          ? today
          : new Date(existing.programLocation.program.startDate);

      const merged = { ...existing, ...updated };
      const payloads = generateSessionsForSchedule(
        existing.programLocationId,
        {
          id: updated.id,
          dayOfWeek: merged.dayOfWeek,
          startTime: merged.startTime,
          endTime: merged.endTime ?? undefined,
          duration: merged.duration,
          type: merged.type,
        },
        start,
        programEnd,
      );

      if (payloads.length > 0) {
        await prisma.programSession.createMany({ data: payloads });
      }

      return updated;
    });
  }

  /**
   * Deletes a schedule and all its future sessions.
   */
  async remove(id: string) {
    await this.findOne(id);

    const today = new Date();
    today.setUTCHours(0, 0, 0, 0);

    await this.prisma.$transaction(async (prisma) => {
      await prisma.programSession.deleteMany({
        where: { scheduleId: id, date: { gte: today } },
      });

      await prisma.programSchedule.delete({ where: { id } });
    });
  }
}
